// This file is automatically generated by Codapt.ai
// Changes you make manually will be overwritten
// Re-generate this file by running `npx codapt@latest generate`

import { createTRPCRouter } from "@/server/api/trpc";

const proceduresRouter = createTRPCRouter({
  // No procedures yet
});

export default proceduresRouter;
